# Generated by Django 5.1.3 on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("non_repudiation", "0002_document_doc_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="jwt",
            field=models.TextField(null=True),
        ),
    ]
